<!-- $_GLOBALS	Contains all global variables.
$_SERVER	Information about headers, paths, and script locations.
$_GET	Variables sent via URL parameters.
$_POST	Variables sent via HTTP POST.
$_FILES	Files uploaded via HTTP POST.
$_COOKIE	Variables passed via cookies.
$_SESSION	Variables stored in the session.
$_REQUEST	Variables from GET, POST, and COOKIE.
$_ENV	Environment variables.
$php_errormsg	The last error message generated by PHP (requires track_errors to be enabled). -->

<?php 

$name = "Alice";
function greet() {
    echo "Hello, " . $GLOBALS['name'];
}
greet();  // Output: Hello, Alice

echo $_GET['name'];
echo $_POST['username'];
// Assuming a file input named 'profile_pic' in a form
echo $_FILES['profile_pic']['name'];  // Output: The original name of the uploaded file
// Assuming a cookie named 'user_id' was set
echo $_COOKIE['user_id'];  // Output: The value of 'user_id' cookie

session_start();
$_SESSION['username'] = 'Alice';
echo $_SESSION['username'];  // Output: Alice



// If there’s an input field named 'email' from either GET, POST, or COOKIE
echo $_REQUEST['email'];  // Output: The value of 'email' parameter


echo $_ENV['PATH'];  // Output: The system PATH environment variable
echo getenv('PATH');











?>